### PR TITLE
fix: thread safe problem of SparseArray in NoDatabaseImpl

### LINKED ISSUE #1225: java.lang.ArrayIndexOutOfBoundsException: length=11; index=11
线上友盟统计到的问题，目前有三个手机遇到。
java.lang.ArrayIndexOutOfBoundsException: length=11; index=11
	at android.util.SparseArray.gc(SparseArray.java:203)
	at android.util.SparseArray.put(SparseArray.java:238)
	at com.liulishuo.filedownloader.database.b.a(NoDatabaseImpl.java:107)
	at com.liulishuo.filedownloader.database.c.a(RemitDatabase.java:137)
	at com.liulishuo.filedownloader.download.DownloadLaunchRunnable.a(DownloadLaunchRunnable.java:680)
	at com.liulishuo.filedownloader.download.DownloadLaunchRunnable.run(DownloadLaunchRunnable.java:303)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:784)

看了一下NoDatabaseImpl.java的源码，感觉是SparseArray非线程安全导致的。
某一个线程在remove，另一个线程在put。
这边是否需要加锁？
final SparseArray<List<ConnectionModel>> connectionModelListMap = new SparseArray<>();

### PR DESCRIPTION
**Pull request by rantianhua**
Closes #1225

### CODE REVIEW

File: library/src/main/java/com/liulishuo/filedownloader/database/NoDatabaseImpl.java [hunk 1]
```diff
@@ -66,49 +66,58 @@ public static Maker createMaker() {
...
 
     @Override
     public List<ConnectionModel> findConnectionModel(int id) {
         final List<ConnectionModel> resultList = new ArrayList<>();
-        final List<ConnectionModel> processList = connectionModelListMap.get(id);
-        if (processList != null) resultList.addAll(processList);
-
+        synchronized (connectionModelListMap) {
+            final List<ConnectionModel> processList = connectionModelListMap.get(id);
+            if (processList != null) resultList.addAll(processList);
```
Comment (Jacksgong) [inline library/src/main/java/com/liulishuo/filedownloader/database/NoDatabaseImpl.java]: no need on the scope

Comment (rantianhua) [reply library/src/main/java/com/liulishuo/filedownloader/database/NoDatabaseImpl.java]: DONE
