### PR TITLE
fix: cannot start a foreground service if there is no any waiting task

### LINKED ISSUE #1209: 更新到1.7.6版本后，通知栏仍概率性自动出现FileDownloader is running提示，不能复现
更新到1.7.6版本后，通知栏仍概率性自动出现FileDownloader is running提示，点击该通知提示没有响应。该提示是在用户使用手机并未下载资源的时候自动出现，手机未重启放置一晚第二天看这个通知又自动消失了。目前暂未获取到有效log。

### PR DESCRIPTION
**Pull request by rantianhua**
Closes #1209

### CODE REVIEW

File: library/src/main/java/com/liulishuo/filedownloader/services/BaseFileServiceUIGuard.java [hunk 1]
```diff
@@ -157,7 +158,10 @@ public void bindStartByContext(final Context context, final Runnable connectedRu
             bindContexts.add(context);
         }
 
-        runServiceForeground = FileDownloadUtils.needMakeServiceForeground(context);
+        boolean needMakeServiceForeground = FileDownloadUtils.needMakeServiceForeground(context);
+        boolean haveWaitingTask =
+                FileDownloader.getImpl().getLostConnectedHandler().haveWaitingTask();
+        runServiceForeground = needMakeServiceForeground && haveWaitingTask;
```
Comment (Jacksgong) [inline library/src/main/java/com/liulishuo/filedownloader/services/BaseFileServiceUIGuard.java]: `needMakeServiceForeground && haveWaitingTask` means not only need FileDownloadUtils configured but also meet has waiting task, which not the same of the title of MR said.

Comment (rantianhua) [reply library/src/main/java/com/liulishuo/filedownloader/services/BaseFileServiceUIGuard.java]: The title just description the problem, I will change it.

Comment (rantianhua) [reply library/src/main/java/com/liulishuo/filedownloader/services/BaseFileServiceUIGuard.java]: Updated!
