### PR TITLE
fix: pause all makes a notification showing

### LINKED ISSUE #1136: Occur [FileDownloader is running] notification despite there is no downloading task.
device：honor
Android: 8.0.0
FileDownload: 1.7.6-SNAPSHOT
description: 
通知栏出现此通知且关不掉，我是在1.7.5版本就遇见这个问题了，后来参照https://github.com/lingochamp/FileDownloader/issues/1096 升级了快照版本问题还是存在

### PR DESCRIPTION
**Pull request by rantianhua**
Closes #1136

### CODE REVIEW

File: library/src/main/java/com/liulishuo/filedownloader/PauseAllMarker.java [hunk 1]
```diff
@@ -0,0 +1,63 @@
...
+            FileDownloadLog.e(PauseAllMarker.class, "create marker file failed", e);
+        }
+    }
+
+    private static File markerFile(Context context) {
+        return new File(context.getCacheDir() + File.separator + MAKER_FILE_NAME);
+    }
+
+    public static boolean isMarked(Context context) {
+        return markerFile(context).exists();
```
Comment (Jacksgong) [inline library/src/main/java/com/liulishuo/filedownloader/PauseAllMarker.java]: Please don't create File instance each time for the same path.

File: library/src/main/java/com/liulishuo/filedownloader/services/FileDownloadService.java [hunk 2]
```diff
@@ -67,6 +78,37 @@ public void onCreate() {
...
+        PauseAllMarker.clearMarker(this);
+    }
+
+    private void stopPauseAllLooperCheck() {
+        pauseAllHandler.removeMessages(PAUSE_ALL_CHECKER_WHAT);
+        pauseAllChecker.quit();
+    }
+
+    @Override
+    public boolean handleMessage(Message msg) {
```
Comment (Jacksgong) [inline library/src/main/java/com/liulishuo/filedownloader/services/FileDownloadService.java]: Please consider moving this looper handler and all about this pauseAll looper to the `PauseAllMarker` class, it would be let `FileDownloadServer` more simple and `PauseAllMarker` more cohesion.

**Comment by carozhu** [comment]
还是会有通知栏显示Runinng问题。
设备：三星S轻奢版
