### PR TITLE
fix show notification issues in demo

### LINKED ISSUE #1224: notification not appear
#### Before Issue

1. Please search on the [Issues](https://github.com/lingochamp/FileDownloader/issues)
2. Please search on the [wiki](https://github.com/lingochamp/FileDownloader/wiki)
3. Please set `FileDownloadLog.NEED_LOG=true` and review the Logcat output from main process and `:filedownloader` process ( pay attention to Warn and Error level logcat)

#### Issue

1. What problem do you get? _notification not appear on 1.7.5 version_

>P.S. If you don't know how to get `:filedownloader` process, it's recommended to using `pidcat` to just filter all your application logcat, or define `process.non-separate=true` on [filedownloader.properties](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties)

---

请在Issue前认真的跟进上面提到的建议，这样将可以极大的加快你遇到问题的处理。

### PR DESCRIPTION
**Pull request by rantianhua**
Closes #1224

### CODE REVIEW

File: demo/src/main/java/com/liulishuo/filedownloader/demo/NotificationSampleActivity.java [hunk 1]
```diff
@@ -136,127 +182,96 @@ protected boolean disableNotification(BaseDownloadTask task) {
...
-            builder.setContentTitle(getTitle())
-                    .setContentText(desc);
-
-
-            if (statusChanged) {
-                builder.setTicker(desc);
-            }
-
-            builder.setProgress(getTotal(), getSofar(), !isShowProgress);
+            builder.setContentTitle(getTitle()).setContentText(desc);
```
Comment (Jacksgong) [inline demo/src/main/java/com/liulishuo/filedownloader/demo/NotificationSampleActivity.java]: why remove `setTicker` operation when the status changed?

Comment (rantianhua) [reply demo/src/main/java/com/liulishuo/filedownloader/demo/NotificationSampleActivity.java]: I think the "ticker" text which is sent to accessibility services is unnecessary for our sample.
