### PR TITLE
fix: close automation redirects of HttpUrlConnection

### LINKED ISSUE #1295: FileDownloader下载某些源必现报错！[已提供下载链接可复现]
## Before Issue

1. 针对fileDownloader的chunk问题 [Issues](https://github.com/lingochamp/FileDownloader/issues/1238)
2. 在OkDownload中出现的问题 [Issues](https://github.com/lingochamp/okdownload/issues/31)

## Issue
**现在遇到上面的两个问题了。我下载了这些链接：**
https://traffic.omny.fm/d/clips/61af0f78-644a-4500-9792-a89500ea78e5/5c2d07fe-0ef9-4b04-9646-a9d20148a726/94c08e35-dc0a-4aa8-b31b-aaf6001fa4bd/audio.mp3?utm_source=Podcast&in_playlist=e62e19db-f740-456f-b0a6-a9d2014b5993&t=1572400611

https://downloads.wamu.org/mp3/dr/19/10/r1191015.mp3

**最终都得到了这样的错误反馈：**
### require range[xxxxxx-) with contentLength(xxxxxxx), but the backend response contentLength is xxxxxxx on downloadId[-xxxxxxx]-connectionIndex[2], please ask your backend dev to fix such problem.

当时OkDownload的作者让我使用单线程来下是可以解决这个问题的。前阵子咨询过你们同样的问题。**针对fileDownloader的chunk问题** [Issues](https://github.com/lingochamp/FileDownloader/issues/1238) 说是已经解决了，但是现在问题好像依然存在？

### PR DESCRIPTION
**Pull request by rantianhua**
Closes #1295

### CODE REVIEW

File: library/src/main/java/com/liulishuo/filedownloader/connection/FileDownloadUrlConnection.java [hunk 1]
```diff
@@ -46,6 +46,9 @@ public FileDownloadUrlConnection(URL url, Configuration configuration) throws IO
         } else {
             mConnection = url.openConnection();
         }
+        if (mConnection instanceof HttpURLConnection) {
```
Comment (Jacksgong) [inline library/src/main/java/com/liulishuo/filedownloader/connection/FileDownloadUrlConnection.java]: why close?

Comment (rantianhua) [reply library/src/main/java/com/liulishuo/filedownloader/connection/FileDownloadUrlConnection.java]: HttpURLConnection will handle redirect automatically, in this way, FileDownloader cannot get redirect url, then use original url to start fetching but get a 302 response.  There is two problems, if the file size is fixed, there is duplicated connection; if the file size is dynamic(different source), the file size is wrong and cannot download successful, like #1295.
