### PR TITLE
fix: maintain database may cause anr

### LINKED ISSUE #1152: ANR on FileDownloadService
at com.liulishuo.filedownloader.download.CustomComponentHolder.maintainDatabase (CustomComponentHolder.java:240)
  at com.liulishuo.filedownloader.download.CustomComponentHolder.getDatabaseInstance (CustomComponentHolder.java:91)
  at com.liulishuo.filedownloader.services.FileDownloadManager.<init> (FileDownloadManager.java:53)
  at com.liulishuo.filedownloader.services.FileDownloadService.onCreate (FileDownloadService.java:63)

Make ANR on my App. 
v 1.7.5

### PR DESCRIPTION
**Pull request by rantianhua**
Closes #1152

### CODE REVIEW

File: library/src/main/java/com/liulishuo/filedownloader/download/CustomComponentHolder.java [hunk 1]
```diff
@@ -88,7 +88,15 @@ public FileDownloadDatabase getDatabaseInstance() {
         synchronized (this) {
             if (database == null) {
                 database = getDownloadMgrInitialParams().createDatabase();
-                maintainDatabase(database.maintainer());
+                // There is no reusable thread for this action and this action has
+                // a very low frequency, so, a new thread is simplest way to make this action
+                // run on background thread.
+                new Thread(new Runnable() {
```
Comment (Jacksgong) [inline library/src/main/java/com/liulishuo/filedownloader/download/CustomComponentHolder.java]: provide thread name, please.

Comment (Jacksgong) [reply library/src/main/java/com/liulishuo/filedownloader/download/CustomComponentHolder.java]: FileDownloadUtils.getThreadPoolName

Comment (rantianhua) [reply library/src/main/java/com/liulishuo/filedownloader/download/CustomComponentHolder.java]: Done
